services:
  - type: web
    name: nsl-kdd-dashboard
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn core.wsgi:application
    envVars:
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.11.9" # <-- CAMBIA ESTO
      - key: SECRET_KEY
        generateValue: true
